### ISSUE TITLE
Pending Work

### ISSUE THREAD

**Issue by rktjmp** [Tuxified/tree-sitter-elixir#10]
I don't want to double dip on what you might be doing. Is there anything you would like me to take a try at?

**Comment by Tuxified** [comment]
There's one thing I've really struggled with (and keep putting off to fully fix it): properly recognizing "qualified function calls". I think the problem lies a bit in how Elixir module names resemble function calls since both (can) have a dot in them. The simplest example being: `App.Module.function([1,2,3])`. Instead of recognizing `App.Module` as the module name only one part is recognized.

If there's anything else you'd like to try, feel free to create an issue and call dibs on it ;)

**Comment by Tuxified** [comment]
Closing this one as I've created some issues if folks would like to chime in. let me know if I missed something
